services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app/
    env_file:
     - ./.env
  db:
    image: postgres:15
    volumes:
     - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=odina
      - POSTGRES_USER=odina
      - POSTGRES_DB=chatbot_db
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
  
volumes:
  postgres_data: